### ISSUE TITLE
Quitar enlaces de la url

### ISSUE THREAD

**Issue by SidVal** [SidVal/csap#7]
Nico, fijate si podes quitar los enlaces que traen los comentaristas.
Te subí el código del JS aca:
https://github.com/SidVal/csap/blob/master/js/blogger-comments.js

***

## Ejemplo
Si le das una mirada a [este artículo](http://www.consultoria-sap.com/2017/01/error-DB278-borrar-variante-protegida.html), en la parte de comentarios, vas a ver que cada autor tiene un enlace a su perfil. Quiero que informe el autor, pero borrarle la URL. Que no se vea. :1st_place_medal:

**Comment by nicolasegp** [comment]
https://github.com/SidVal/csap/blob/master/js/blogger-comments.js#L42

Cambiar:
```js
profileUrl: (auth.uri ? auth.uri.$t : undefined),
```

Por:
```js
profileUrl: undefined,
```

---

Aunque veo que si se quita esto podría dañar la validación en:
https://github.com/SidVal/csap/blob/master/js/blogger-comments.js#L102
ya que valida al autor por medio de
```js
comment.author.name
comment.author.profileUrl
```

---

lo otro seria buscar en el html la etiqueta <a> y quitarle el href

**Comment by SidVal** [comment]
> lo otro seria buscar en el html la etiqueta y quitarle el href

No tiene nada en html, es como si procesara todo desde el script. 
Es muy raro. Fijate en la página que te dejé de ejemplo y te vas a dar cuenta:

Fijate:

`view-source:http://www.consultoria-sap.com/2017/01/error-DB278-borrar-variante-protegida.html`
Linea: 882 en adelante
